export type GalleryWithImages = {
  id: number;
  year: number;
  titleHu: string;
  titleEn: string;
  sourceUrl: string;
  highlighted: boolean;
  images: string[];
  tags: string[];
};

export const galleries: GalleryWithImages[] = [
  {
    id: 3,
    year: 2017,
    titleHu: 'Harmony Mysore Hét',
    titleEn: 'Harmony Mysore Week',
    sourceUrl: 'https://mula.bandha.works/images/2017-HARMONY-MYSORE-WEEK/',
    highlighted: false,
    images: [],
    tags: ['newshala', 'mysore', 'harmony'],
  },
  {
    id: 2,
    year: 2016,
    titleHu: 'David Robson Mysore Terem',
    titleEn: 'David Robson Mysore Room',
    sourceUrl: 'https://mula.bandha.works/images/2016-DAVID-ROBSON_MYSORE-ROOM/',
    highlighted: true,
    images: [],
    tags: ['oldshala', 'mysore', 'davidrobson'],
  },
  {
    id: 7,
    year: 2014,
    titleHu: 'Laruga Astanga Hétvége',
    titleEn: 'Laruga Ashtanga Weekend',
    sourceUrl: 'https://mula.bandha.works/images/2014-LARUGA-ASHTANGA-WEEKEND/',
    highlighted: false,
    images: [],
    tags: ['oldshala', 'mysore', 'workshop', 'laruga'],
  },
  {
    id: 8,
    year: 2014,
    titleHu: 'Petros Jivamukti workshop',
    titleEn: 'Petros Jivamukti Workshop',
    sourceUrl: 'https://mula.bandha.works/images/2014-PETROS-JIVAMUKTI-WEEKEND/',
    highlighted: false,
    images: [],
    tags: ['oldshala', 'workshop', 'petros'],
  },
  {
    id: 2,
    year: 2016,
    titleHu: 'David Robson Astanga Workshop - 2016',
    titleEn: 'David Robson Workshop',
    sourceUrl: 'https://mula.bandha.works/images/2016-DAVID-ROBSON-WORKSHOP/',
    highlighted: true,
    images: [],
    tags: ['oldshala', 'mysore', 'davidrobson'],
  },
  {
    id: 4,
    year: 2018,
    titleHu: 'Harmony Mysore Hét',
    titleEn: 'Harmony Mysore Week',
    sourceUrl: 'https://mula.bandha.works/images/2018-HARMONY-MYSORE-WEEK/',
    highlighted: false,
    images: [],
    tags: ['newshala', 'mysore', 'harmony'],
  },
  {
    id: 5,
    year: 2018,
    titleHu: 'Új Shala Tűz Ceremónia',
    titleEn: 'New Shala Fire Ceremony',
    sourceUrl: 'https://mula.bandha.works/images/2018-FIRE-CEREMONY/',
    highlighted: false,
    images: [],
    tags: ['newshala', 'fireceremony'],
  },
  {
    id: 6,
    year: 2018,
    titleHu: 'Santina Mysore Hét',
    titleEn: 'Santina Mysore Week',
    sourceUrl: 'https://mula.bandha.works/images/2018-SANTINA-MYSORE-WEEK/',
    highlighted: false,
    images: [],
    tags: ['newshala', 'mysore', 'santina'],
  },
  {
    id: 9,
    year: 2024,
    titleHu: 'Ross Astanga Hét',
    titleEn: 'Ross Ashtanga Week',
    sourceUrl: 'https://mula.bandha.works/images/2024-ROSS-WORKSHOP/',
    highlighted: true,
    images: [],
    tags: ['oldshala', 'mysore', 'davidrobson'],
  },
  {
    id: 10,
    year: 2014,
    titleHu: 'Dr. Sjoman Workshop',
    titleEn: 'Dr. Sjoman Workshop',
    sourceUrl: 'https://mula.bandha.works/images/2014-DR-SJOMAN-WORKSHOP/',
    highlighted: true,
    images: [],
    tags: ['oldshala', 'workshop', 'drsjoman'],
  },
  {
    id: 11,
    year: 2016,
    titleHu: 'Mysore Jógaászana Verseny',
    titleEn: 'Mysore Yogasana Competition',
    sourceUrl: 'https://mula.bandha.works/images/2016-MYSORE-YOGASANA-COMPETITION/',
    highlighted: true,
    images: [],
    tags: ['oldshala', 'yogasana', 'competition'],
  },
  {
    id: 12,
    year: 2017,
    titleHu: 'Santina Mysore Hét',
    titleEn: 'Santina Mysore Week',
    sourceUrl: 'https://mula.bandha.works/images/2017-SANTINA-MYSORE-WEEK/',
    highlighted: true,
    images: [],
    tags: ['oldshala', 'mysore', 'santina'],
  },
  {
    id: 13,
    year: 2014,
    titleHu: 'Mysore Magic',
    titleEn: 'Mysore Magic',
    sourceUrl: 'https://mula.bandha.works/images/MYSORE-MAGIC/',
    highlighted: true,
    images: [],
    tags: ['street', 'mysore', 'india'],
  },
];
