backend:
  name: git-gateway
  repo: code-istvan/bw
  branch: main
  site_domain: 'https://voluble-crumble-cbe048.netlify.app'
media_folder: src/images/uploads
public_folder: src/images/uploads
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: blog
    label: Blog Posts
    label_singular: Blog
    folder: src/content/blog/
    create: true
    slug: '{{slug}}'
    extension: .md
    format: frontmatter
    fields:
      - label: Published
        name: published
        widget: boolean
        default: true
      - label: 'Language'
        name: 'language'
        widget: 'select'
        options: ['Hungarian', 'English']
        default: 'Hungarian'
      - label: Title
        name: title
        widget: string
      - label: Title Background
        name: titleBackground
        widget: boolean
        default: false
        required: false
      - label: Canonical URL
        name: canonical
        widget: string
        required: false
      - label: 'Canonical Language'
        name: 'canonicalLanguage'
        widget: 'select'
        options: ['Hungarian', 'English']
        required: false
      - label: Description
        name: description
        widget: string
      - label: Author
        name: author
        widget: relation
        collection: authors
        value_field: name
        display_fields:
          - name
        search_fields:
          - name
          - email
      - label: Tags
        name: tags
        widget: list
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: image
        widget: image
      - label: Featured Image Mobil
        name: imageMobil
        widget: image
      - label: Body
        name: body
        widget: markdown
  - name: authors
    label: Authors
    label_singular: Blog
    folder: src/content/authors/
    media_folder: ''
    public_folder: ''
    extension: json
    format: json
    create: true
    slug: '{{name}}'
    fields:
      - label: Name
        name: name
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Email
        name: email
        widget: string
        required: false
      - label: Image
        name: authorimage
        widget: image
        required: false
  - name: schedule
    label: Schedule
    label_singular: Schedule
    folder: src/content/schedule/
    extension: json
    format: json
    create: true
    identifier_field: date
    slug: '{{date}}'
    fields:
      - label: Published
        name: published
        widget: boolean
        default: true
      - label: Date
        name: date
        widget: datetime
        date_format: 'YYYY.MM.DD'
        format: 'LL'
        picker_utc: false
      - label: Fullmoon
        name: fullmoon
        widget: boolean
        default: false
        required: false
      - label: Newmoon
        name: newmoon
        widget: boolean
        default: false
        required: false
      - label: Ekadashi
        name: ekadashi
        widget: boolean
        default: false
        required: false
      - label: Class
        name: class
        widget: relation
        collection: classes
        value_field: classId
        display_fields: ['class', ('classId')]
        search_fields: ['class', 'classId']
      - label: Teacher
        name: teacher
        widget: relation
        collection: teachers
        value_field: teacherId
        display_fields: ['teacher', ('teacherId')]
        search_fields: ['teacher', 'teacherId']
      - label: Class Time
        name: classTime
        widget: relation
        collection: customTime
        value_field: customTime
        display_fields: ['customTime']
        search_fields: ['customTime']
      - label: Class2
        name: class2
        widget: relation
        collection: classes
        value_field: classId
        display_fields: ['class', ('classId')]
        search_fields: ['class', 'classId']
        default: null
        required: false
      - label: Teacher2
        name: teacher2
        widget: relation
        collection: teachers
        value_field: teacherId
        display_fields: ['teacher', ('teacherId')]
        search_fields: ['teacher', 'teacherId']
        default: null
        required: false
      - label: Class Time2
        name: classTime2
        widget: relation
        collection: customTime
        value_field: customTime
        display_fields: ['customTime']
        search_fields: ['customTime']
        default: null
        required: false
      - label: Class3
        name: class3
        widget: relation
        collection: classes
        value_field: classId
        display_fields: ['class', ('classId')]
        search_fields: ['class', 'classId']
        default: null
        required: false
      - label: Teacher3
        name: teacher3
        widget: relation
        collection: teachers
        value_field: teacherId
        display_fields: ['teacher', ('teacherId')]
        search_fields: ['teacher', 'teacherId']
        default: null
        required: false
      - label: Class Time3
        name: classTime3
        widget: relation
        collection: customTime
        value_field: customTime
        display_fields: ['customTime']
        search_fields: ['customTime']
        default: null
        required: false
      - label: Class4
        name: class4
        widget: relation
        collection: classes
        value_field: classId
        display_fields: ['class', ('classId')]
        search_fields: ['class', 'classId']
        default: null
        required: false
      - label: Teacher4
        name: teacher4
        widget: relation
        collection: teachers
        value_field: teacherId
        display_fields: ['teacher', ('teacherId')]
        search_fields: ['teacher', 'teacherId']
        default: null
        required: false
      - label: Class Time4
        name: classTime4
        widget: relation
        collection: customTime
        value_field: customTime
        display_fields: ['customTime']
        search_fields: ['customTime']
        default: null
        required: false

  - name: classes
    label: Classes
    label_singular: Schedule
    folder: src/content/classes/
    extension: json
    format: json
    create: true
    slug: '{{classId}}'
    fields:
      - { label: Classid, name: classId, widget: string }
      - { label: Class, name: class, widget: string }
      - { label: Class-Name-HU, name: classHu, widget: string }
      - { label: Class-Name-EN, name: classEn, widget: string }
      - { label: Class-Detail-HU, name: classDetailHu, widget: string, required: false }
      - { label: Class-Detail-EN, name: classDetailEn, widget: string, required: false }
      - { label: Class-Sign-Up-Url, name: classSignUpUrl, widget: string, required: false }
  - name: customTime
    label: Custom time
    label_singular: Schedule
    folder: src/content/customTimes/
    extension: json
    format: json
    create: true
    slug: '{{customTime}}'
    fields:
      - { label: Custom time, name: customTime, widget: string }
  - name: teachers
    label: Teachers
    folder: src/content/teachers/
    format: 'json'
    create: true
    slug: '{{teacherId}}'
    fields:
      - { label: Published, name: published, widget: boolean, default: true }
      - { label: Teacher-Order, name: teacherOrder, widget: number, required: false }
      - { label: Teacher-Id, name: teacherId, widget: string }
      - { label: Teacher, name: teacher, widget: string }
      - { label: Teacher-Link, name: teacherLink, widget: string, required: false }
      - { label: Teacher-Image, name: teacherImage, widget: image, required: false }
      - { label: Hu-Teacher-FullName, name: huTeacherFullName, widget: string, required: false }
      - { label: En-Teacher-FullName, name: enTeacherFullName, widget: string, required: false }
      - { label: Hu-Teacher-Style, name: huTeacherStyle, widget: string, required: false }
      - { label: En-Teacher-Style, name: enTeacherStyle, widget: string, required: false }
      - { label: Hu-Teacher-Title, name: huTeacherTitle, widget: string, required: false }
      - { label: En-Teacher-Title, name: enTeacherTitle, widget: string, required: false }

  - name: events
    label: Events
    folder: src/content/events/
    format: 'json'
    create: true
    slug: '{{eventid}}'
    fields:
      - { label: Published, name: published, widget: boolean, default: true }
      - { label: Featured, name: featured, widget: boolean, default: true }
      - {
          label: Esemény típusa,
          name: eventType,
          widget: select,
          options: [Tanfolyam, Workshop, Konferencia, Tábor, Egyéb közösségi, SharathDzsi],
        }
      - { label: Eventid, name: eventid, widget: string }
      - { label: Date, name: date, widget: datetime }
      - { label: Title, name: title, widget: string }
      - { label: Title in English, name: titleEnglish, widget: string }
      - { label: Image, name: eventimage, widget: image, required: false }
      - { label: Shortdescription, name: shortdescription, widget: text, required: false }
      - { label: Shortdescription in English, name: shortdescriptionEnglish, widget: text, required: false }
      - { label: Eventlink, name: eventlink, widget: string, required: false }
      - { label: Eventlink in English, name: eventlinkEnglish, widget: string, required: false }
      - {
          label: Teacher,
          name: teacher,
          widget: relation,
          collection: teachers,
          value_field: teacherId,
          display_fields: ['teacher', ('teacherId')],
          search_fields: ['teacher', 'teacherId'],
        }
