backend:
  name: git-gateway
  repo: code-istvan/bw
  branch: main
  site_domain: 'https://voluble-crumble-cbe048.netlify.app'
media_folder: src/images/uploads
public_folder: src/images/uploads
slug:
  encoding: ascii
  clean_accents: true
  sanitize_replacement: '-'
collections:
  - name: blog
    label: Blog Posts
    label_singular: Blog
    folder: src/content/blog/
    create: true
    slug: '{{slug}}'
    extension: .md
    format: frontmatter
    fields:
      - label: Published
        name: published
        widget: boolean
        default: true
      - label: Title
        name: title
        widget: string
      - label: Description
        name: description
        widget: string
      - label: Author
        name: author
        widget: relation
        collection: authors
        value_field: name
        display_fields:
          - name
        search_fields:
          - name
          - email
      - label: Tags
        name: tags
        widget: list
      - label: Publish Date
        name: date
        widget: datetime
      - label: Featured Image
        name: image
        widget: image
      - label: Featured Image Mobil
        name: imageMobil
        widget: image
      - label: Body
        name: body
        widget: markdown
  - name: authors
    label: Authors
    label_singular: Blog
    folder: src/images/uploads/authors/
    media_folder: ''
    public_folder: ''
    extension: json
    format: json
    create: true
    slug: '{{name}}'
    fields:
      - label: Name
        name: name
        widget: string
      - label: Title
        name: title
        widget: string
      - label: Email
        name: email
        widget: string
        required: false
      - label: Image
        name: authorimage
        widget: image
        required: false
  - name: schedule
    label: Schedule
    label_singular: Schedule
    folder: src/content/schedule/
    extension: json
    format: json
    create: true
    identifier_field: date
    slug: '{{date}}'
    fields:
      - label: Published
        name: published
        widget: boolean
        default: true
      - label: Date
        name: date
        widget: datetime
        date_format: 'YYYY.MM.DD'
        format: 'LL'
        picker_utc: false
      - label: Fullmoon
        name: fullmoon
        widget: boolean
        default: false
        required: false
      - label: Newmoon
        name: newmoon
        widget: boolean
        default: false
        required: false
      - label: Ekadashi
        name: ekadashi
        widget: boolean
        default: false
        required: false
      - label: ClassTest
        name: classTest
        widget: relation
        collection: classes
        value_field: classId
        display_fields: ['class', 'classId']
        search_fields: ['class', 'classId']
  - name: classes
    label: Classes
    label_singular: Schedule
    folder: src/content/classes/
    extension: json
    format: json
    create: true
    slug: '{{classId}}'
    fields:
      - { label: Classid, name: classId, widget: string }
      - { label: Class, name: class, widget: string }
      - { label: Shortescription, name: shortDescription, widget: 'markdown', required: false }
      - { label: Signup, name: signup, widget: string, required: false }
  - name: customDates
    label: Custom dates
    label_singular: Schedule
    folder: src/content/customDates/
    extension: json
    format: json
    create: true
    slug: '{{customDate}}'
    fields:
      - { label: Custom date, name: customDate, widget: string }
